### ISSUE TITLE
Errno 71 when running pebble & certbot Docker containers on Vagrant+VirtualBox

### ISSUE THREAD

**Issue by kvjava1** [letsencrypt/pebble#311]
On my Windows10 machine, I'm using Vagrant and VirtualBox with Ubuntu 18.04 Vagrant box, which has Docker 19.03.5 installed.

I have a **docker-compose.yml** which has both pebble and certbot services defined:

```
  certbot:
    image: certbot/certbot:v1.4.0
    entrypoint: "certbot certonly --webroot -w /var/www/certbot --email test@test.com -d this.is.test.com --rsa-key-size 4096 --agree-tos --force-renewal --non-interactive --server https://0.0.0.0:14000/dir --no-verify-ssl"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  pebble:
    image: letsencrypt/pebble:v2.3.0
    ports:
      - 14000:14000  # ACME port
      - 15000:15000  # Management port
    environment:
      - PEBBLE_VA_NOSLEEP=1
```
I'm basically trying to simulate certbot running locally, using pebble instead of the real/live LetsEncrypt CA, and verify everything locally before deploying only the 'certbot' service (with nginx) in prod.

When I bring up my Docker containers, certbot is displaying the following:

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
An unexpected error occurred:
OSError: [Errno 71] Protocol error: '/etc/letsencrypt/accounts/0.0.0.0:14000'
Please see the logfiles in /var/log/letsencrypt for more details.
```

Has anyone else seen this when trying to use certbot and pebble locally?

Thank you very much.
