### ISSUE TITLE
Getting /roots/0 certificate from a different k8s container

### ISSUE THREAD

**Issue by mstaicu** [letsencrypt/pebble#373]
I have a k8s cluster, where I have an instance of **Pebble** and an instance of **Traefik** that acts as an ingress controller. I managed to get **Traefik's** LEGO ACME client to get **Pebble's** ACME server root CA in order to setup an ACME challenge that will let me issue certificates for **Traefik** every time I spin up the cluster

In a different pod, I have a container that runs a **nodejs** process, which I need it to make requests to **Traefik** via port 443, i.e. HTTPS

The problem is that if I mount the same hard coded **Pebble** ACME server root CA ( **pebble.minica.pem** ) on the file system of the container which runs my **nodejs** process, and then I reference the absolute path of **pebble.minica.pem** as the value of the **NODE_EXTRA_CA_CERTS** environment variable, I get failing HTTPS requests with invalid certificate errors

What works are the root certificates found at **https://{domain-of-pebble-in-my-k8-cluster}:15000/roots/0**. If I download the root CA found at that URL, then reference that file in **NODE_EXTRA_CA_CERTS**, then all my HTTPS requests issued from my **nodejs** process succeed

Since those root and intermediate certificates are generated at runtime by Pebble, and since Pebbles' **https://pebble:15000/roots/0** turns out to be self signed, what would be the best way of retrieving the root certificate, in order for me to use it in any container that needs to perform HTTPS requests to the service that has a certificate with the root certificate as part of its chain?

**Comment by felixfontein** [comment]
Somehow your description reads that you are using Pebble for something it is not designed for, and against which the README explicitly warns: anything else than testing an ACME client / system.

If you are actually testing some ACME client or ACME-based system, you could simply disable certificate checking to retrieve the root certificate.

**Comment by mstaicu** [comment]
Can you elaborate on this please?

`you could simply disable certificate checking to retrieve the root certificate.`

**Comment by jsha** [comment]
For instance, you could `curl --insecure https://{domain-of-pebble-in-my-k8-cluster}:15000/roots/0 --output pebble-root.pem`

**Comment by mstaicu** [comment]
> For instance, you could `curl --insecure https://{domain-of-pebble-in-my-k8-cluster}:15000/roots/0 --output pebble-root.pem`

I thought about that, especially in a container lifecycle hook ( `PostStart` ) but was reluctant in favour of other, potentially more ergonomic, solutions. The issue now is for the `pebble` container to be up and running before querying it AND to install additional dependencies in `alpine` based images ( such as `curl` )

**Comment by mstaicu** [comment]
Right so, this works, but doesn't look very clean

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      automountServiceAccountToken: false
      containers:
        - name: client
          image: client-remix
          envFrom:
            - secretRef:
                name: dotenv
          env:
            - name: NODE_EXTRA_CA_CERTS
              value: /certs/pebble-root-ca.pem
          lifecycle:
            postStart:
              exec:
                command:
                  [
                    "/bin/sh",
                    "-c",
                    "apk add curl && mkdir /certs && curl --insecure https://pebble:15000/roots/0 --output /certs/pebble-root-ca.pem",
                  ]
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
```

Plus that, now, I get the following in the logs on container startup

```
[client] Warning: Ignoring extra certs from `/certs/pebble-root-ca.pem`, load failed: error:80000002:system library::No such file or directory
```

**Comment by mstaicu** [comment]
Final solution, for now

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      automountServiceAccountToken: false
      containers:
        - name: client
          image: client-remix
          envFrom:
            - secretRef:
                name: dotenv
          env:
            - name: NODE_EXTRA_CA_CERTS
              value: /certs/pebble-root-ca.pem
          volumeMounts:
            - name: certs
              mountPath: /certs
      initContainers:
        - name: client-wait-for-pebble
          image: alpine/curl
          command: ["/bin/sh", "-c"]
          args:
            [
              'while [[ "$(curl --insecure -s -o /dev/null -w %{http_code} https://pebble:15000/roots/0)" != "200" ]]; do echo "Waiting for Pebble..."; sleep 5; done',
            ]
        - name: client-get-root-certs
          image: alpine/curl
          command: ["/bin/sh", "-c"]
          args:
            [
              "curl --insecure -s -o /certs/pebble-root-ca.pem https://pebble:15000/roots/0",
            ]
          volumeMounts:
            - name: certs
              mountPath: /certs
      volumes:
        - name: certs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
```
