### ISSUE TITLE
Outdated docker image

### ISSUE THREAD

**Issue by dkossako** [letsencrypt/pebble#394]
Hello,

last version of pebble based on tags is 2.4.0, but last in [docker hub](https://hub.docker.com/r/letsencrypt/pebble/tags) is 2.3.1. Is there any chance to update it?

**Comment by tindzk** [comment]
As a temporary workaround, you can use the Docker container provided by akrantz01:
```shell
docker pull us-central1-docker.pkg.dev/krantz-dev-default/pebble/pebble:latest
```

Alternatively, if you prefer to build the Pebble container from source, follow these steps instead:
```shell
git clone https://github.com/letsencrypt/pebble.git
cd pebble
docker build -t local/pebble-git --file docker/pebble/linux.Dockerfile .
```

**Comment by Cilenco** [comment]
With docker compose you can also do:

```yml
services:
  pebble:
    build: 
      context: https://github.com/letsencrypt/pebble.git#v2.4.0
      dockerfile: docker/pebble/linux.Dockerfile
```
