### ISSUE TITLE
Docker: Use hostname instead of IP addresses

### ISSUE THREAD

**Issue by shred** [letsencrypt/pebble#453]
Is it possible to use hostnames as parameters, instead of IP addresses?

Currently, the docker-compose file uses a subnet and fixed IP addresses. I cannot set up a docker network in my integration tests though (long story), so I have to do ugly workarounds.

With hostnames instead of IPs, this would be possible (if I'm not mistaken):

```
version: "3"
services:
  pebble:
    image: ghcr.io/letsencrypt/pebble:latest
    command: -config test/config/pebble-config.json -strict -dnsserver challtestsrv:8053
    ports:
      - 14000:14000
      - 15000:15000
  challtestsrv:
    image: ghcr.io/letsencrypt/pebble-challtestsrv:latest
    command: -defaultIPv6 "" -defaultIPv4 challtestsrv
    ports:
      - 8055:8055
```
