### ISSUE TITLE
Valid authorizations still have all challenges

### ISSUE THREAD

**Issue by sophie-h** [letsencrypt/pebble#88]
>    challenges (required, array of objects):  For pending authorizations,
      the challenges that the client can fulfill in order to prove
      possession of the identifier.  For final authorizations (in the
      "valid" or "invalid" state), the **challenges that were used**.
      …
      For final authorizations, it contains the challenges that were
      **successfully completed**.

Note, that I have proposed to change this to removing all other challenges in the moment of a successful response to a challenge.

```yaml
{
   "status": "valid",
   "identifier": {
      "type": "dns",
      "value": "localhost"
   },
   "challenges": [
      {
         "type": "http-01",
         "url": "https://localhost:14000/chalZ/f6mGRSNQZ8BhrPnly_lyIsvPZX9PT-7dPRpfbv1GfpU",
         "token": "kzOKCd_DWD8wMbld35v5kn352Y_JebrgH2vkkHHz42c",
         "status": "valid",
         "validated": "2018-01-09T16:30:35Z"
      },
      {
         "type": "tls-sni-02",
         "url": "https://localhost:14000/chalZ/eG6J4H-CB2nELjdbVidbbgBn_QwGlp5tn2rwxmjuyCc",
         "token": "l45tM-Gp2F61oUkmKANcsQCSdF59AS591C5u4s1Wxrg",
         "status": "pending"
      },
      {
         "type": "dns-01",
         "url": "https://localhost:14000/chalZ/blaIxirG-OM_2WnMOTE4YjDEnyo22YwMt1KjtksIBjA",
         "token": "Zs_Zuc3kyCUekGLH66cxp_jxjtsmXLe1uT8ZfwKRwWU",
         "status": "pending"
      }
   ],
   "expires": "2018-01-09T17:30:35Z"
}
```
